# Generated by Django 4.1.7 on 2023-04-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_and_site_settings', '0002_licenseplates_whitelist_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicensePlates',
            new_name='LicensePlate',
        ),
        migrations.AlterModelOptions(
            name='licenseplate',
            options={'verbose_name': 'License plate', 'verbose_name_plural': 'License plates'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name': 'License plate', 'verbose_name_plural': 'License plates'},
        ),
    ]
