# Generated by Django 4.1.7 on 2023-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License_plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=40, null=True, verbose_name='License plate')),
                ('region', models.CharField(blank=True, max_length=20, null=True, verbose_name='Region')),
                ('date_time', models.DateTimeField(verbose_name='Date and time')),
                ('user_name', models.CharField(max_length=50, verbose_name='User name')),
                ('field_name', models.ImageField(upload_to=None, verbose_name='Image')),
                ('source', models.CharField(max_length=30, verbose_name='Source')),
            ],
        ),
    ]
